/* Generated by build.js — do not edit. */
'use strict';
const CACHE = 'ksilofon-2b17dcfb13';
const PRECACHE = [
  "/",
  "/404.html",
  "/song/yonatan-hakatan/",
  "/song/twinkle-twinkle/",
  "/song/mary-had-a-little-lamb/",
  "/song/uga-uga/",
  "/song/hine-ma-tov/",
  "/song/nad-ned/",
  "/song/yom-huledet-sameach/",
  "/song/row-row-row-your-boat/",
  "/song/london-bridge/",
  "/song/ode-to-joy/",
  "/song/parpar-nechmad/",
  "/song/haoto-shelanu/",
  "/song/yadaim-lemala/",
  "/song/akavish-katanchik/",
  "/song/aviron/",
  "/song/yakinton/",
  "/song/eretz-yisrael-sheli/",
  "/song/dugit-nosaat/",
  "/song/rakefet/",
  "/song/hashkedia-porachat/",
  "/song/ani-purim/",
  "/song/jingle-bells/",
  "/song/old-macdonald/",
  "/styles.css?v=2b17dcfb13",
  "/songs.js?v=2b17dcfb13",
  "/analytics.js?v=2b17dcfb13",
  "/audio.js?v=2b17dcfb13",
  "/app.js?v=2b17dcfb13",
  "/favicon-32.png",
  "/favicon.svg",
  "/apple-touch-icon.png",
  "/manifest.webmanifest",
  "/icon-192.png",
  "/icon-512.png"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.hostname.includes('umami')) return; // analytics: never cached, fails silently offline

  // Navigations: network-first so new deploys are picked up immediately;
  // cached page (or home) as offline fallback.
  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request).catch(() =>
        caches.match(url.pathname.endsWith('/') || url.pathname === '' ? url.pathname || '/' : url.pathname + '/')
          .then(r => r || caches.match(url.pathname))
          .then(r => r || caches.match('/'))
      )
    );
    return;
  }

  // Same-origin assets are content-versioned → cache-first is always safe.
  // Fonts (Google) get the same treatment after first use.
  e.respondWith(
    caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
      if (res.ok && (url.origin === location.origin || url.hostname.endsWith('gstatic.com') || url.hostname.endsWith('googleapis.com'))) {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return res;
    }))
  );
});
